name: Update ECB Data

# This schedule triggers the workflow at 17:15 (5:15 PM) Monday to Friday
on:
  schedule:
    - cron: '15 17 * * 1-5'  # Run at 17:15 from Monday to Friday
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  fetch-ecb-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch ECB data
        run: |
          curl -o data/eurofxref-daily.xml https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml

      - name: Commit updated ECB data
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/eurofxref-daily.xml
          git commit -m "Update ECB exchange rates"
          git push
